name: first workflow

on:
  push:
    branches:
      - main
      - master
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Welcome Message!!
        run: echo "Welcome out first GitHub Actions"
      - name: Checkout repo
        uses: actions/checkout@v5.0.0
      - name: List files
        run: ll && la -la
